function lineChart(id,series,opt){var el=document.getElementById(id);if(!el)return;var W=860,H=260,pl=44,pr=12,pt=12,pb=28;var xs=series[0].pts.map(function(p){return p[0];});var all=[].concat.apply([],series.map(function(s){return s.pts.map(function(p){return p[1];});}));
  var ymin=opt.ymin!=null?opt.ymin:Math.min.apply(null,all),ymax=Math.max.apply(null,all);if(ymax===ymin)ymax=ymin+1;ymax=ymax+(ymax-ymin)*0.08;var X=function(i){return pl+(W-pl-pr)*i/(xs.length-1);},Y=function(v){return H-pb-(H-pt-pb)*(v-ymin)/(ymax-ymin);};
  var s='<svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+escH(opt.label)+'">';for(var t=0;t<=4;t++){var v=ymin+(ymax-ymin)*t/4,y=Y(v);s+='<line x1="'+pl+'" x2="'+(W-pr)+'" y1="'+y+'" y2="'+y+'" stroke="#e5e2db"/><text x="'+(pl-6)+'" y="'+(y+4)+'" text-anchor="end" font-size="11" fill="#6b6760">'+(opt.fmt?opt.fmt(v):Math.round(v))+'</text>';}
  xs.forEach(function(x,i){var lab_=x.length===7?(x.slice(5)==='01'?x.slice(0,4):''):(x.slice(8)==='01'&&(xs.length<=400||x.slice(5,7)==='01')?(x.slice(5,7)==='01'?x.slice(0,4):['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][+x.slice(5,7)]):'');if(lab_)s+='<text x="'+X(i)+'" y="'+(H-8)+'" text-anchor="middle" font-size="11" fill="#6b6760">'+lab_+'</text>';});
  series.forEach(function(se){s+='<polyline fill="none" stroke="'+se.color+'" stroke-width="2"'+(se.dash?' stroke-dasharray="'+se.dash+'"':'')+' points="'+se.pts.map(function(p,i){return X(i)+','+Y(p[1]);}).join(' ')+'"/>';});
  s+='<rect x="'+pl+'" y="'+pt+'" width="'+(W-pl-pr)+'" height="'+(H-pt-pb)+'" fill="transparent" class="hov"/></svg>';
  el.innerHTML='<div class="lg">'+series.map(function(se){return '<span><i style="background:'+se.color+(se.dash?';background:repeating-linear-gradient(90deg,'+se.color+' 0 4px,transparent 4px 7px)':'')+'"></i>'+escH(se.name)+'</span>';}).join('')+'</div><div style="position:relative">'+s+'<div class="cx-tip" style="display:none"></div></div>';
  var svg=el.querySelector('svg'),tip=el.querySelector('.cx-tip');svg.addEventListener('mousemove',function(e){var r=svg.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,i=Math.max(0,Math.min(xs.length-1,Math.round((x-pl)/(W-pl-pr)*(xs.length-1))));tip.style.display='block';tip.style.left=((X(i)/W)*r.width+8)+'px';tip.style.top='8px';tip.innerHTML=escH(xs[i])+': '+series.map(function(se){return escH(se.name)+' '+(opt.fmt?opt.fmt(se.pts[i][1]):se.pts[i][1]);}).join(' &middot; ');});svg.addEventListener('mouseleave',function(){tip.style.display='none';});}
function barChart(id,cats,series,opt){var el=document.getElementById(id);if(!el)return;var W=860,H=260,pl=48,pr=12,pt=14,pb=28,n=cats.length,k=series.length;var all=[].concat.apply([],series.map(function(s){return s.vals;}));var ymax=Math.max.apply(null,all)*1.1||1;
  var gw=(W-pl-pr)/n,bw=Math.max(4,(gw-10)/k-2),Y=function(v){return H-pb-(H-pt-pb)*v/ymax;};var s='<svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+escH(opt.label)+'">';
  for(var t=0;t<=4;t++){var v=ymax*t/4,y=Y(v);s+='<line x1="'+pl+'" x2="'+(W-pr)+'" y1="'+y+'" y2="'+y+'" stroke="#e5e2db"/><text x="'+(pl-6)+'" y="'+(y+4)+'" text-anchor="end" font-size="11" fill="#6b6760">'+(opt.fmt?opt.fmt(v):Math.round(v).toLocaleString())+'</text>';}
  cats.forEach(function(c,i){var x0=pl+gw*i+5;s+='<text x="'+(pl+gw*i+gw/2)+'" y="'+(H-8)+'" text-anchor="middle" font-size="11" fill="#6b6760">'+escH(c)+'</text>';series.forEach(function(se,j){var v=se.vals[i]||0,x=x0+j*(bw+2),y=Y(v);s+='<rect x="'+x+'" y="'+y+'" width="'+bw+'" height="'+(H-pb-y)+'" rx="3" fill="'+se.color+'"><title>'+escH(c)+': '+escH(se.name)+' '+(opt.fmt?opt.fmt(v):v.toLocaleString())+'</title></rect>';if(k<=2&&n<=8)s+='<text x="'+(x+bw/2)+'" y="'+(y-4)+'" text-anchor="middle" font-size="10" fill="#333">'+(opt.fmt?opt.fmt(v):v.toLocaleString())+'</text>';});});
  s+='</svg>';el.innerHTML='<div class="lg">'+series.map(function(se){return '<span><i style="background:'+se.color+';height:10px"></i>'+escH(se.name)+'</span>';}).join('')+'</div>'+s;}
function subStyle(r){r=String(r||'').trim().toUpperCase().replace('X','');var m={A:'#0039A6',C:'#0039A6',E:'#0039A6',B:'#FF6319',D:'#FF6319',F:'#FF6319',M:'#FF6319','4':'#00933C','5':'#00933C','6':'#00933C','1':'#EE352E','2':'#EE352E','3':'#EE352E',N:'#FCCC0A',Q:'#FCCC0A',R:'#FCCC0A',W:'#FCCC0A',J:'#996633',Z:'#996633',L:'#A7A9AC',S:'#808183',G:'#6CBE45'};var bg=m[r]||'#111';return {bg:bg,fg:(r==='N'||r==='Q'||r==='R'||r==='W')?'#111':'#fff'};}
function subBullets(routes){return String(routes||'').split(/\s+/).filter(Boolean).map(function(r){var st=subStyle(r);return '<span class="subway-route-badge" style="background:'+st.bg+';color:'+st.fg+'">'+escH(r.replace('X',''))+'</span>';}).join('');}
function busPill(r,c){return '<span class="bus-route-badge'+(/SBS/i.test(r)?' sbs':'')+'"'+(c?' style="background:'+escH(c)+'"':'')+'>'+escH(String(r).replace('-SBS',' SBS'))+'</span>';}
function hbar(id,rows,opt){var el=document.getElementById(id);if(!el)return;var W=860,rh=24,pl=300,pr=60,H=rows.length*rh+10,mx=Math.max.apply(null,rows.map(function(r){return r[1];}))||1;var s='<svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+escH(opt.label)+'">';
  rows.forEach(function(r,i){var y=5+i*rh,w=(W-pl-pr)*r[1]/mx;s+='<a href="#map" onclick="pickBlk('+r[2]+')"><text x="'+(pl-8)+'" y="'+(y+16)+'" text-anchor="end" font-size="11.5" fill="#0d1b4b" font-weight="700">'+escH(r[0])+'</text><rect x="'+pl+'" y="'+(y+4)+'" width="'+w+'" height="'+(rh-8)+'" rx="3" fill="'+opt.color+'"><title>'+escH(r[0])+': '+r[1].toLocaleString()+'</title></rect><text x="'+(pl+w+6)+'" y="'+(y+16)+'" font-size="11" fill="#333">'+r[1].toLocaleString()+'</text></a>';});
  el.innerHTML=s+'</svg>';}
